// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://prynzfnbkapkrysbziyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InByeW56Zm5ia2Fwa3J5c2J6aXl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMjY5MjUsImV4cCI6MjA3MjgwMjkyNX0.jknhDZ0sd9wfHM9Auh1hKDnWcF8J3cr-g5Z8aAwHChA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});